id: d3c956d3009b4ae3aa7f20fec0c87f30
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
  language: en
  author: ''
  volume: {}
